services:
  selenium-hub:
    image: selenium/hub:4.12.0-20230926
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
    environment:
      - SE_GRID_MAX_SESSION=10
      - SE_GRID_BROWSER_TIMEOUT=300
      - SE_GRID_NODE_HEALTHCHECK_TIMEOUT=300

  node-chrome:
    image: selenium/node-chrome:4.12.0-20230926
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    depends_on:
      - selenium-hub
    networks:
      - grid

  node-firefox:
    image: selenium/node-firefox:4.12.0-20230926
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5
    depends_on:
      - selenium-hub
    networks:
      - grid

networks:
  grid
